### ISSUE TITLE
Option to toggle on/off specific items from the list.

### ISSUE THREAD

**Issue by Stidnoob** [Gogo1951/Open-Sesame#10]
Can we have an option to toggle on/off specific items from the list, while in-game?

**Comment by Gogo1951** [comment]
No... sorry. I think that's out of scope for this project. But you can easily go to the LUA file and comment out items.

Out of curiosity, what items would you like to disable?

**Comment by Stidnoob** [comment]
I found the option in the LUA thanks... Only the fishing trunks.. I'm participating in the hardcore all-star event and let just say alot of fishing was involved. And keeping the trunks unopened but opening the clams automatically saved me alot of bag space
