### ISSUE TITLE
Error: GetContainerNumSlots' (a nil value)

### ISSUE THREAD

**Issue by nerolite** [Gogo1951/Open-Sesame#16]
I am seeing the following error message on Wow Classic Era.

`Message: Interface/AddOns/Open-Sesame/Open-Sesame_Vanilla.lua:233: attempt to call global 'GetContainerNumSlots' (a nil value)`

The addon is no longer opening any containers. Any suggestion on how to resolve it?

**Comment by nerolite** [comment]
Oh, looks like there has been an API change:
https://us.forums.blizzard.com/en/wow/t/api-replacement-for-getcontainernumslots/1404085

> C_Container.GetContainerNumSlots
> 
> Most of the container calls got pulled into C_Container.

**Comment by MyTechnoHunter** [comment]
correct, era API is merged in most things with wrath/dragonflight now. i will push an update soon

**Comment by MyTechnoHunter** [comment]
PR waiting with fix for this

**Comment by nerolite** [comment]
Great to hear, much appreciated!

**Comment by RichDawg50** [comment]
I hope a fix is in the works. Really miss this great addon.
