### ISSUE TITLE
WOW Classic Tallonkai's Jewel gets stuck on cursor

### ISSUE THREAD

**Issue by fireymerlin** [Gogo1951/Open-Sesame#19]
This addon keeps trying to open the item which causes it to get stuck on the cursor.  Iwas unable to do much other than to /logout and disable this addon.  The quest is Ferocitas the Dream Eater.  The item number is 8049.

**Comment by Gogo1951** [comment]
Added more checks to make sure it doesn't try and open while it's opening.
