### ISSUE TITLE
WoW Classic Era (1.15.4) - Addon no longer properly working

### ISSUE THREAD

**Issue by maximus210793** [Gogo1951/Open-Sesame#26]
Hi,
Could you update it to the latest Classic Era Game  Version of 1.15.4, since the addon is no longer working properly?
Would be awesome, thanks a lot in advance!

**Comment by Gogo1951** [comment]
Hey @maximus210793,

I am not willing to launch this quite yet, but I do have a working version for Classic.

Added a delete function too that's... a work in progress but it will delete your lowest value gray, or white (trash white), or (trash) consumable that's 10 levels or lower below your level. Also working on deleting quest items / items provided for quests when quests are completed.

Anyway code is checked in, but very much a beta.

![image](https://github.com/user-attachments/assets/3d9ed1e7-1fa7-4f37-8e32-c7638f6b91ba)
