### ISSUE TITLE
.lua error on Rogue ( not in combat ) when I tried to open Reinforced Junkbox

### ISSUE THREAD

**Issue by sth666** [Gogo1951/Open-Sesame#8]
**Hi.
 I just want to leave here the .lua error that showed up for me Today.** 

```
1x [ADDON_ACTION_FORBIDDEN] AddOn 'Open-Sesame' tried to call the protected function 'UNKNOWN()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `UseContainerItem'
[string "@Open-Sesame/Open-Sesame_Wrath.lua"]:469: in function `AutomaticOpener'
[string "@Open-Sesame/Open-Sesame_Wrath.lua"]:432: in function `?'
[string "@Open-Sesame/Open-Sesame_Wrath.lua"]:3: in function <Open-Sesame/Open-Sesame_Wrath.lua:3>
```

**Cheers.**

**Comment by Gogo1951** [comment]
I'll look into this. An excuse to level my rogue this weekend! (=

**Comment by MyTechnoHunter** [comment]
can you give more details? was this while looting a corpse? did you have more than one box? was this locked? as much info as you can give would be helpful!

**Comment by sth666** [comment]
> can you give more details? was this while looting a corpse? did you have more than one box? was this locked? as much info as you can give would be helpful!

**Hello there, I come back soon from work, so when I log in  game, I will try to caught everything and later I send information here.**

**Comment by sth666** [comment]
_**Hello there sorry for late answer**_ :)

**I found issue .**

_When I try open (locked) Reinforced Junkbox, I forgot that I use a macro to open the boxes instantly ( I have **Glyph of Pick Lock** ) but when I try open Reinforced Junkbox by Pick Lock from spellbook, the .lua error **didn't show up.**_

_My Macro is_ : 
```
/use Reinforced Junkbox
/use Reinforced Junkbox
/use Pick Lock
/use Reinforced Junkbox
/use Reinforced Junkbox
```

_**Thanks for quickly response about my issue.**_

_**Take care and i wish for both of You all the Best ! :)**_

**Comment by Gogo1951** [comment]
Ok, it's fucked for Rogues at the moment.

**Comment by Gogo1951** [comment]
Two issues... constantly in combat... it says "locked" when you have items you aren't high enough skill to open.

And then it sells lockboxes to vendors. Oof.

Easy fix... take lockboxes off the whitelist. Harder fix... figure out why they have special behavior that ignores the other rules we have in place.
